highlighter: rouge
markdown: kramdown
kramdown:
  entity_output: symbol
permalink: none
destination: site
exclude: ['README.md', 'content', 'LICENSE', 'Gemfile', 'Gemfile.lock']
keep_files: ['docs', 'static', 'llms.txt']
url: https://spark.apache.org
