name: Build HTML

description: Set up Ruby and run the Jekyll build.

inputs:
  ruby-version:
    description: Ruby version to use.
    required: false
    default: "3.4"

runs:
  using: composite
  steps:
  - name: Set up Ruby and Bundler
    uses: ruby/setup-ruby@v1
    with:
      ruby-version: ${{ inputs.ruby-version }}
      # This will use the version of Bundler specified in `Gemfile.lock`.
      bundler-cache: true
  - name: Run documentation build
    shell: bash
    run: bundle exec jekyll build
