name: Build HTML

on:
  pull_request:
    branches:
    - asf-site

jobs:
  build:
    name: build HTML
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout Spark Website repository
      uses: actions/checkout@v7
    - name: Set up Ruby and Bundler
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4'
        bundler-cache: true
    - name: Run documentation build
      run: bundle exec jekyll build
