name: Generate and Push HTML

on:
  push:
    branches:
    - asf-site
    # TODO: Remove after testing.
    - automated-html

jobs:
  commit:
    name: build and commit HTML to asf-site
    if: "!contains(github.event.head_commit.message, '[html]')"
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
    - name: Checkout Spark Website repository
      uses: actions/checkout@v7
    - name: Set up Ruby and Bundler
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4'
        bundler-cache: true
    - name: Run documentation build
      run: bundle exec jekyll build
    - name: Commit and push generated HTML
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        # `-f` because we told git to otherwise ignore `site/`
        git add -f site/
        if git diff --cached --quiet; then
          echo "No changes to commit."
        else
          COMMIT_TITLE=$(git log -1 --pretty=%s)
          git commit -m "[html] $COMMIT_TITLE"
          git push
        fi
