name: Build HTML

on:
  pull_request:
    branches:
    - asf-site

jobs:
  build:
    name: Build HTML
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout Spark Website repository
      uses: actions/checkout@v7
    - name: Build HTML
      uses: ./.github/actions/build-html
