name: Lint

on: pull_request

jobs:
  release-notes:
    name: Release Notes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Lint release notes
        run: python3 .dev/lint-release-notes.py
